// Mocks generated by Mockito 5.4.6 from annotations
// in rox_proxy/test/certificate_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:rox_proxy/models/domain_rule.dart' as _i4;
import 'package:rox_proxy/services/proxy_channel.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCaStatus_0 extends _i1.SmartFake implements _i2.CaStatus {
  _FakeCaStatus_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProxyChannel].
///
/// See the documentation for Mockito's code generation for more information.
class MockProxyChannel extends _i1.Mock implements _i2.ProxyChannel {
  MockProxyChannel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i2.ExchangeEvent> get exchangeStream =>
      (super.noSuchMethod(
            Invocation.getter(#exchangeStream),
            returnValue: _i3.Stream<_i2.ExchangeEvent>.empty(),
          )
          as _i3.Stream<_i2.ExchangeEvent>);

  @override
  _i3.Future<int> startProxy({
    required int? port,
    required List<_i4.DomainRule>? domainRules,
    required int? connectionTimeoutSeconds,
    required bool? setSystemProxy,
    required bool? httpsInterceptionEnabled,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startProxy, [], {
              #port: port,
              #domainRules: domainRules,
              #connectionTimeoutSeconds: connectionTimeoutSeconds,
              #setSystemProxy: setSystemProxy,
              #httpsInterceptionEnabled: httpsInterceptionEnabled,
            }),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> stopProxy() =>
      (super.noSuchMethod(
            Invocation.method(#stopProxy, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> configureSystemProxy({
    required bool? enabled,
    required int? port,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#configureSystemProxy, [], {
              #enabled: enabled,
              #port: port,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String> getProxyState() =>
      (super.noSuchMethod(
            Invocation.method(#getProxyState, []),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#getProxyState, []),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<bool> installCACertificate() =>
      (super.noSuchMethod(
            Invocation.method(#installCACertificate, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> checkCATrust() =>
      (super.noSuchMethod(
            Invocation.method(#checkCATrust, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<_i2.CaStatus> getCAStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getCAStatus, []),
            returnValue: _i3.Future<_i2.CaStatus>.value(
              _FakeCaStatus_0(this, Invocation.method(#getCAStatus, [])),
            ),
          )
          as _i3.Future<_i2.CaStatus>);

  @override
  _i3.Future<_i6.Uint8List?> fetchBody(String? ref) =>
      (super.noSuchMethod(
            Invocation.method(#fetchBody, [ref]),
            returnValue: _i3.Future<_i6.Uint8List?>.value(),
          )
          as _i3.Future<_i6.Uint8List?>);

  @override
  _i3.Future<void> releaseBody(String? ref) =>
      (super.noSuchMethod(
            Invocation.method(#releaseBody, [ref]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> releaseAllBodies() =>
      (super.noSuchMethod(
            Invocation.method(#releaseAllBodies, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i6.Uint8List?> decompressBody(
    _i6.Uint8List? data,
    String? encoding,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#decompressBody, [data, encoding]),
            returnValue: _i3.Future<_i6.Uint8List?>.value(),
          )
          as _i3.Future<_i6.Uint8List?>);
}
